TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += tti355.db
DATA += tti355.proto

#=======================================
include $(TOP)/configure/RULES
